#!/usr/bin/env bash
#getting domain name info
if [ "$#" -eq 1 ]; then
    echo "$(dig www.$1 | awk '/ANSWER SECTION:/ {getline; print "The subdomain www is a "$4" record and points to "$5}')"
    echo "$(dig lb-01.$1 | awk '/ANSWER SECTION:/ {getline; print "The subdomain lb-01 is a "$4" record and points to "$5}')"
    echo "$(dig web-01.$1 | awk '/ANSWER SECTION:/ {getline; print "The subdomain web-01 is a "$4" record and points to "$5}')"
    echo "$(dig web-02.$1 | awk '/ANSWER SECTION:/ {getline; print "The subdomain web-02 is a "$4" record and points to "$5}')"
elif [ "$#" -eq 2 ]; then
    echo "$(dig $2.$1 | awk '/ANSWER SECTION:/ {getline; print "The subdomain '"$2"' is a "$4" record and points to "$5}')"
fi