#!/usr/bin/env bash
#script to install nginix and litsen to port 80

sudo apt update
sudo apt-get -y install nginx
service nginx start
sudo sh -c 'echo "HelloWorld!" > /var/www/html/index.nginx-debian.html'
service nginx restart