#!/usr/bin/env bash
#script to install nginix and litsen to port 80

sudo apt update
sudo apt-get -y install nginx
sudo service nginx start
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo service nginx restart