#!/usr/bin/env bash
#story of passwd

while IFS=":" read -r username password uid gid comment home shell
do
	echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid place is protected by the passcode $password, more info about the user here: $comment"
done < /etc/passwd
