#!/usr/bin/env bash
# @ 8 print good luck @ 4 print bad luck

a="Best School"
i=1
while [ $i -le 10 ]
do
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	else
		echo "$a"
	fi
	i=$((i + 1))
done
