#!/usr/bin/env bash
#bash script to give me info about school

search="school"

	if [ ! -e "$search" ]
	then
		echo "school file does not exist"
	else
		echo "school file exists"
		if [ -s "$search" ]
		then
			echo "school file is not empty"
		else
			echo "school file is empty"
		fi
		if [ -f "$search" ]
		then
			echo "school is a regular file"
		fi
	fi
