#!/usr/bin/env bash
#run nginx server as nginx user

sudo pkill -f apache2
#create nginx user
sudo adduser --system --no-create-home --disabled-login --group nginx
sudo chmod 644 /etc/nginx/nginx.conf
#add the "user nginx to config file"
sudo sed -i "1i user nginx;" /etc/nginx/nginx.conf
#change http from port 80 to 8080
sudo sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
sudo  service nginx restart